@startuml uml

class 氧气 {
}

class 水 {
}

abstract class 动物 {
 + 有生命
 + 新陈代谢(in o2 : 氧气, in water : 水)
 + 繁殖() 
}

class 鸟 {
    + 羽毛
    + 有角质喙没有牙齿
    + 下蛋()
}

class 翅膀 {
}

interface 飞翔 {
    + 飞()
}

class 大雁 {
    + 下蛋()
    + 飞()
}

class 雁群 {
    + V形飞行()
    + 一形飞行()
}

class 鸭 {
    + 下蛋()
}

class 唐老鸭 {
    + 讲话()
}

class 企鹅 {
    + 下蛋()
}

class 气候 {
}

动物 ..> 水
动物 ..> 氧气
动物 <|-- 鸟
翅膀 <--* 鸟
飞翔 <|.. 大雁
大雁 <--o 雁群
鸟 <|-- 大雁
鸟 <|-- 鸭
鸭 <|-- 唐老鸭
讲人话 ()- 唐老鸭
鸟 <|-- 企鹅
气候<--企鹅

@enduml