@startuml uml
class 简单工厂 {
    + createOperate():运算
}

class 运算 {
    + numberA:double
    + numberB:double
    + getResult():double
}

class 加法 {
    + getResult():double
}

class 减法 {
    + getResult():double
}

class 乘法 {
    + getResult():double
}

class 除法 {
    + getResult():double
}

运算 <|-- 加法
运算 <|-- 减法
运算 <|-- 乘法
运算 <|-- 除法
运算<--简单工厂
@enduml